### ISSUE TITLE
Typescript version constraints

### ISSUE THREAD

**Issue by jasongrout** [phosphorjs/phosphor#169]
Unless we really want to automatically update to Typescript 2.1, the Typescript requirement line at https://github.com/phosphorjs/phosphor/blob/master/package.json#L27 should probably read `"typescript": "~2.0.3",`

**Comment by jasongrout** [comment]
Changing the requirement to `~2.0.3` would be more compatible with typedoc as well.

**Comment by jasongrout** [comment]
(I found this because phosphor doesn't compile now - Typescript 2.1 throws some errors, probably from the improved type inference/checking)

**Comment by sccolbert** [comment]
can you past the compile error you're getting? is that listed in breaking changes for TS 2.1? 

I agree-ish with the version suggestion, but that means JLab will/should do the same (I think).

**Comment by jasongrout** [comment]
> JLab will/should do the same (I think).

Definitely.

**Comment by jasongrout** [comment]
```
% git log -n 1 | head -1
commit ed6c10e483a7aeb71bdd116ca870a9162d895662

% npm install                                                                                                                    master
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prefer global marked@0.3.6 should be installed with -g

> fsevents@1.0.15 install /release/phosphor/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/release/phosphor/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" is installed via remote

> phosphor@0.7.0 prepublish /release/phosphor
> npm run build


> phosphor@0.7.0 build /release/phosphor
> npm run build:src && npm run build:test


> phosphor@0.7.0 build:src /release/phosphor
> tsc --project src

src/ui/keymap.ts(856,12): error TS2322: Type 'ReadonlyArray<string>' is not assignable to type 'string[]'.
  Property 'push' is missing in type 'ReadonlyArray<string>'.
src/ui/vdom.ts(972,49): error TS2345: Argument of type 'ReadonlyArray<any>' is not assignable to parameter of type 'VNode[]'.
  Property 'push' is missing in type 'ReadonlyArray<any>'.
src/ui/vdom.ts(981,5): error TS2322: Type 'ReadonlyArray<any>' is not assignable to type 'any[]'.
  Property 'push' is missing in type 'ReadonlyArray<any>'.
src/ui/vdom.ts(1001,25): error TS2345: Argument of type 'ReadonlyArray<any>' is not assignable to parameter of type 'VNode[]'.
src/ui/vdom.ts(1031,12): error TS2322: Type 'ReadonlyArray<any>' is not assignable to type 'VNode[]'.
```

**Comment by jasongrout** [comment]
> > JLab will/should do the same (I think).
> Definitely.

We already do it: https://github.com/jupyterlab/jupyterlab/blob/master/package.json#L60

**Comment by sccolbert** [comment]
Ah, it looks like they updated `Object.freeze([])` to return a `ReadonlyArray` instead of an `Array`.

**Comment by sccolbert** [comment]
I'm going to close this since we've updated to 2.1. I'd rather keep up to date with new TS releases instead of fixing to a particular version. Since the TS team doesn't really follow semver, it's kind of a moot point anyway.

**Comment by infinity0** [comment]
Was there a commit or commits that updated phosphorjs 0.7.0 to work with the newer TypeScript?

I'm asking because I'm trying to package ipywidgets 6.0.0 which is what SageMath 8.0 uses, and ipywidgets 6.0.0 uses 0.7.0 which I can't build with the latest TS available in Debian (2.2.2), I get the errors mentioned above.

If I can backport 1-4 commits to 0.7.0, this would make my life a lot easier, instead of trying to figure out if 0.7.1 (or some later version) works correctly with ipywidgets 6.0.0.

**Comment by infinity0** [comment]
For reference, the errors are:

~~~~
phosphor-0.7.0$ tsc --project src
src/ui/keymap.ts(856,12): error TS2322: Type 'ReadonlyArray<string>' is not assignable to type 'string[]'.
  Property 'push' is missing in type 'ReadonlyArray<string>'.
src/ui/vdom.ts(972,49): error TS2345: Argument of type 'ReadonlyArray<any>' is not assignable to parameter of type 'VNode[]'.
  Property 'push' is missing in type 'ReadonlyArray<any>'.
src/ui/vdom.ts(981,5): error TS2322: Type 'ReadonlyArray<any>' is not assignable to type 'any[]'.
  Property 'push' is missing in type 'ReadonlyArray<any>'.
src/ui/vdom.ts(1001,25): error TS2345: Argument of type 'ReadonlyArray<any>' is not assignable to parameter of type 'VNode[]'.
src/ui/vdom.ts(1031,12): error TS2322: Type 'ReadonlyArray<any>' is not assignable to type 'VNode[]'.
(unstable-amd64-sbuild)infinity0@pdeb1:~/var/lib/jupyter/phosphor-0.7.0$ tsc --version
Version 2.1.6
~~~~

**Comment by infinity0** [comment]
For reference, cherry-picking f8f118db26c9660cf3c6b6e4797f8ecc5315ffd1 fixed the build.

It also looks like the 0.7.0 from npm that ipywidgets uses, has additionally 5f6f8828ed20a341d7e41871edd806734dac71f6 on top of the 0.7.0 tag here on github.
